# Generated by Django 4.2.3 on 2023-08-30 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organizations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "website",
                    models.URLField(blank=True, max_length=128, null=True, unique=True),
                ),
                ("logo", models.ImageField(upload_to=organizations.models.get_dir)),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "linkedin",
                    models.URLField(blank=True, max_length=100, null=True, unique=True),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, max_length=100, null=True, unique=True),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, max_length=100, null=True, unique=True),
                ),
                ("tagline", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
