# Generated by Django 4.2.3 on 2023-08-30 21:13

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=organizations.models.get_dir
            ),
        ),
    ]
