# Generated by Django 4.2.3 on 2023-08-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="challenge1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SF", "Securing funding"),
                    ("PD", "Product design and development"),
                    ("BC", "Building a customer base"),
                    ("BS", "Business strategy and planning"),
                    ("MB", "Marketing and branding"),
                    ("SO", "Scaling operations"),
                    ("MF", "Managing finances"),
                    ("LR", "Legal and regulatory compliance"),
                    ("HT", "Hiring talent"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="challenge2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SF", "Securing funding"),
                    ("PD", "Product design and development"),
                    ("BC", "Building a customer base"),
                    ("BS", "Business strategy and planning"),
                    ("MB", "Marketing and branding"),
                    ("SO", "Scaling operations"),
                    ("MF", "Managing finances"),
                    ("LR", "Legal and regulatory compliance"),
                    ("HT", "Hiring talent"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="challenge3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SF", "Securing funding"),
                    ("PD", "Product design and development"),
                    ("BC", "Building a customer base"),
                    ("BS", "Business strategy and planning"),
                    ("MB", "Marketing and branding"),
                    ("SO", "Scaling operations"),
                    ("MF", "Managing finances"),
                    ("LR", "Legal and regulatory compliance"),
                    ("HT", "Hiring talent"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="funding",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TR", "Transportation"),
                    ("PH", "Pharmaceutical"),
                    ("TL", "Telecommunications"),
                    ("MF", "Manufacturing"),
                    ("MI", "Mining"),
                    ("HO", "Hospitality"),
                    ("MN", "Media and News"),
                    ("AG", "Agriculture"),
                    ("TE", "Technology"),
                    ("ED", "Education"),
                    ("FI", "Finance"),
                    ("HC", "Health Care"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ID", "Idea"),
                    ("DV", "Development"),
                    ("PR", "Pre-Launch"),
                    ("PO", "Post-Launch"),
                ],
                default=("ID", "Idea"),
                max_length=2,
                null=True,
            ),
        ),
    ]
