# Generated by Django 4.2.3 on 2023-08-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0003_organization_challenge1_organization_challenge2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="funding",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EF", "Exploring funding opportunities"),
                    ("PS", "Pre-seed Stage"),
                    ("SA", "Series A Round"),
                    ("SR", "Seed Round"),
                    ("SB", "Series B or Beyond"),
                    ("NF", "Not Currently Seeking Funding"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
