# Generated by Django 4.2.3 on 2024-01-03 20:27

from django.db import migrations, models
import django_countries.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('organizations', '0004_alter_organization_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.AddField(
            model_name='organization',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industries',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1,000', '501-1,000'), ('1,001-5,000', '1,001-5,000'), ('5,001-10,000', '5,001-10,000'), ('10,001+', '10,001+')], max_length=100, null=True),
        ),
    ]
