# Generated by Django 4.2.3 on 2024-01-03 20:42

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('organizations', '0005_remove_organization_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='industries',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
