# Generated by Django 4.2.3 on 2025-01-13 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0006_alter_organization_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pending_requests',
            field=models.ManyToManyField(blank=True, related_name='requested_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
