# Generated by Django 4.2.3 on 2023-08-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organizations",
            field=models.ManyToManyField(blank=True, to="organizations.organization"),
        ),
    ]
