# Generated by Django 4.2.3 on 2024-01-03 20:27

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_funding'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organizations',
        ),
        migrations.AddField(
            model_name='user',
            name='leadership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
