# Generated by Django 4.2.3 on 2024-11-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('VACATION', 'Vacation'), ('LEAVE', 'Leave')], default='ACTIVE', help_text='Current status of the user in their organization team', max_length=10),
        ),
    ]
