# Generated by Django 4.2.3 on 2024-12-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coowner',
            field=models.IntegerField(blank=True, help_text='Organization ID that the user co-owns', null=True),
        ),
    ]
